"""銘柄スクリーナー データベース (カテゴリ別)
en: 英語検索キーワード（ローマ字・英社名・略称）"""

SCREENER: dict = {
    "JP": {
        "電機・半導体": [
            {"ticker": "6758.T", "name": "ソニーグループ",     "en": "sony"},
            {"ticker": "6861.T", "name": "キーエンス",         "en": "keyence"},
            {"ticker": "6857.T", "name": "アドバンテスト",     "en": "advantest"},
            {"ticker": "8035.T", "name": "東京エレクトロン",   "en": "tokyo electron tel"},
            {"ticker": "6920.T", "name": "レーザーテック",     "en": "lasertec"},
            {"ticker": "6645.T", "name": "オムロン",           "en": "omron"},
            {"ticker": "6702.T", "name": "富士通",             "en": "fujitsu"},
            {"ticker": "6701.T", "name": "NEC",                "en": "nec"},
            {"ticker": "6752.T", "name": "パナソニック",       "en": "panasonic"},
            {"ticker": "6971.T", "name": "京セラ",             "en": "kyocera"},
            {"ticker": "6963.T", "name": "ローム",             "en": "rohm"},
            {"ticker": "6594.T", "name": "日本電産",           "en": "nidec"},
            {"ticker": "6501.T", "name": "日立製作所",         "en": "hitachi"},
            {"ticker": "6503.T", "name": "三菱電機",           "en": "mitsubishi electric"},
            {"ticker": "6506.T", "name": "安川電機",           "en": "yaskawa"},
        ],
        "自動車・輸送機器": [
            {"ticker": "7203.T", "name": "トヨタ自動車",       "en": "toyota motor"},
            {"ticker": "7267.T", "name": "ホンダ",             "en": "honda"},
            {"ticker": "7269.T", "name": "スズキ",             "en": "suzuki"},
            {"ticker": "7201.T", "name": "日産自動車",         "en": "nissan"},
            {"ticker": "7270.T", "name": "SUBARU",             "en": "subaru"},
            {"ticker": "7261.T", "name": "マツダ",             "en": "mazda"},
            {"ticker": "7011.T", "name": "三菱重工業",         "en": "mitsubishi heavy industries mhi"},
            {"ticker": "7013.T", "name": "IHI",                "en": "ihi"},
            {"ticker": "6326.T", "name": "クボタ",             "en": "kubota"},
            {"ticker": "7751.T", "name": "キヤノン",           "en": "canon"},
        ],
        "銀行・金融": [
            {"ticker": "8306.T", "name": "三菱UFJフィナンシャル", "en": "mitsubishi ufj mufg"},
            {"ticker": "8316.T", "name": "三井住友フィナンシャル","en": "sumitomo mitsui smfg"},
            {"ticker": "8411.T", "name": "みずほフィナンシャル", "en": "mizuho"},
            {"ticker": "8591.T", "name": "オリックス",           "en": "orix"},
            {"ticker": "8766.T", "name": "東京海上ホールディングス","en": "tokio marine"},
            {"ticker": "8725.T", "name": "MS&ADインシュアランス", "en": "ms ad insurance"},
            {"ticker": "8604.T", "name": "野村ホールディングス",  "en": "nomura"},
            {"ticker": "8308.T", "name": "りそなホールディングス","en": "resona"},
        ],
        "通信・IT": [
            {"ticker": "9984.T", "name": "ソフトバンクグループ", "en": "softbank"},
            {"ticker": "9432.T", "name": "NTT",                  "en": "ntt nippon telegraph"},
            {"ticker": "9433.T", "name": "KDDI",                 "en": "kddi au"},
            {"ticker": "9434.T", "name": "ソフトバンク",         "en": "softbank"},
            {"ticker": "4385.T", "name": "メルカリ",             "en": "mercari"},
            {"ticker": "4689.T", "name": "LINEヤフー",           "en": "line yahoo z"},
            {"ticker": "3697.T", "name": "SHIFT",                "en": "shift"},
            {"ticker": "4307.T", "name": "野村総合研究所",       "en": "nomura research nri"},
        ],
        "小売・消費": [
            {"ticker": "9983.T", "name": "ファーストリテイリング","en": "fast retailing uniqlo"},
            {"ticker": "3382.T", "name": "セブン&アイ",          "en": "seven eleven ito yokado"},
            {"ticker": "8267.T", "name": "イオン",               "en": "aeon"},
            {"ticker": "2802.T", "name": "味の素",               "en": "ajinomoto"},
            {"ticker": "2914.T", "name": "日本たばこ産業",       "en": "jt japan tobacco"},
            {"ticker": "2503.T", "name": "キリンホールディングス","en": "kirin beer"},
            {"ticker": "2502.T", "name": "アサヒグループ",       "en": "asahi beer"},
            {"ticker": "7453.T", "name": "良品計画",             "en": "muji ryohin keikaku"},
            {"ticker": "3086.T", "name": "J.フロント リテイリング","en": "j front daimaru matsuzakaya"},
        ],
        "ゲーム・エンタメ": [
            {"ticker": "7974.T", "name": "任天堂",               "en": "nintendo"},
            {"ticker": "3659.T", "name": "ネクソン",             "en": "nexon"},
            {"ticker": "9684.T", "name": "スクウェア・エニックス","en": "square enix"},
            {"ticker": "7832.T", "name": "バンダイナムコ",       "en": "bandai namco"},
            {"ticker": "3765.T", "name": "ガンホー",             "en": "gungho"},
            {"ticker": "6460.T", "name": "セガサミー",           "en": "sega sammy"},
            {"ticker": "2432.T", "name": "DeNA",                 "en": "dena"},
            {"ticker": "3632.T", "name": "グリー",               "en": "gree"},
        ],
        "製薬・ヘルスケア": [
            {"ticker": "4568.T", "name": "第一三共",             "en": "daiichi sankyo"},
            {"ticker": "4519.T", "name": "中外製薬",             "en": "chugai pharmaceutical roche"},
            {"ticker": "4523.T", "name": "エーザイ",             "en": "eisai"},
            {"ticker": "4503.T", "name": "アステラス製薬",       "en": "astellas pharma"},
            {"ticker": "4543.T", "name": "テルモ",               "en": "terumo"},
            {"ticker": "4151.T", "name": "協和キリン",           "en": "kyowa kirin"},
            {"ticker": "4507.T", "name": "塩野義製薬",           "en": "shionogi"},
        ],
        "素材・化学": [
            {"ticker": "4063.T", "name": "信越化学工業",         "en": "shin etsu chemical"},
            {"ticker": "4188.T", "name": "三菱ケミカル",         "en": "mitsubishi chemical"},
            {"ticker": "5401.T", "name": "日本製鉄",             "en": "nippon steel"},
            {"ticker": "3407.T", "name": "旭化成",               "en": "asahi kasei"},
            {"ticker": "4005.T", "name": "住友化学",             "en": "sumitomo chemical"},
            {"ticker": "5713.T", "name": "住友金属鉱山",         "en": "sumitomo metal mining"},
        ],
        "不動産・建設": [
            {"ticker": "1925.T", "name": "大和ハウス工業",       "en": "daiwa house"},
            {"ticker": "1928.T", "name": "積水ハウス",           "en": "sekisui house"},
            {"ticker": "8801.T", "name": "三井不動産",           "en": "mitsui fudosan real estate"},
            {"ticker": "8802.T", "name": "三菱地所",             "en": "mitsubishi estate"},
            {"ticker": "8830.T", "name": "住友不動産",           "en": "sumitomo realty"},
            {"ticker": "1963.T", "name": "日揮ホールディングス", "en": "jgc"},
        ],
        "エネルギー・資源": [
            {"ticker": "5020.T", "name": "ENEOSホールディングス","en": "eneos jx nippon oil"},
            {"ticker": "9501.T", "name": "東京電力",             "en": "tepco tokyo electric power"},
            {"ticker": "9531.T", "name": "東京ガス",             "en": "tokyo gas"},
            {"ticker": "1605.T", "name": "INPEX",                "en": "inpex"},
        ],
    },
    "US": {
        "テクノロジー": [
            {"ticker": "AAPL",  "name": "アップル",               "en": "apple"},
            {"ticker": "MSFT",  "name": "マイクロソフト",         "en": "microsoft"},
            {"ticker": "GOOGL", "name": "グーグル",               "en": "google alphabet"},
            {"ticker": "META",  "name": "メタ",                   "en": "meta facebook"},
            {"ticker": "NVDA",  "name": "エヌビディア",           "en": "nvidia"},
            {"ticker": "AMD",   "name": "AMD",                    "en": "amd advanced micro devices"},
            {"ticker": "INTC",  "name": "インテル",               "en": "intel"},
            {"ticker": "ORCL",  "name": "オラクル",               "en": "oracle"},
            {"ticker": "CRM",   "name": "セールスフォース",       "en": "salesforce crm"},
            {"ticker": "ADBE",  "name": "アドビ",                 "en": "adobe"},
            {"ticker": "QCOM",  "name": "クアルコム",             "en": "qualcomm"},
            {"ticker": "TXN",   "name": "テキサス・インスツルメンツ","en": "texas instruments ti"},
            {"ticker": "AVGO",  "name": "ブロードコム",           "en": "broadcom"},
            {"ticker": "ARM",   "name": "アーム",                 "en": "arm holdings"},
            {"ticker": "PLTR",  "name": "パランティア",           "en": "palantir"},
            {"ticker": "SNOW",  "name": "スノーフレーク",         "en": "snowflake"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ",       "en": "supermicro super micro"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ","en": "applied materials"},
            {"ticker": "MU",    "name": "マイクロン",             "en": "micron"},
            {"ticker": "LRCX",  "name": "ラムリサーチ",           "en": "lam research"},
        ],
        "AI・クラウド": [
            {"ticker": "NVDA",  "name": "エヌビディア",           "en": "nvidia"},
            {"ticker": "MSFT",  "name": "マイクロソフト",         "en": "microsoft azure"},
            {"ticker": "GOOGL", "name": "グーグル",               "en": "google alphabet gcp"},
            {"ticker": "AMZN",  "name": "アマゾン",               "en": "amazon aws"},
            {"ticker": "META",  "name": "メタ",                   "en": "meta facebook"},
            {"ticker": "CRM",   "name": "セールスフォース",       "en": "salesforce"},
            {"ticker": "PLTR",  "name": "パランティア",           "en": "palantir"},
            {"ticker": "SNOW",  "name": "スノーフレーク",         "en": "snowflake"},
            {"ticker": "ARM",   "name": "アーム",                 "en": "arm"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ",       "en": "supermicro"},
            {"ticker": "DELL",  "name": "デル・テクノロジーズ",   "en": "dell technologies"},
            {"ticker": "HPE",   "name": "ヒューレット・パッカード","en": "hewlett packard enterprise hpe"},
        ],
        "ヘルスケア": [
            {"ticker": "JNJ",   "name": "ジョンソン＆ジョンソン", "en": "johnson jnj"},
            {"ticker": "UNH",   "name": "ユナイテッドヘルス",     "en": "unitedhealth"},
            {"ticker": "PFE",   "name": "ファイザー",             "en": "pfizer"},
            {"ticker": "MRK",   "name": "メルク",                 "en": "merck"},
            {"ticker": "ABBV",  "name": "アッヴィ",               "en": "abbvie"},
            {"ticker": "LLY",   "name": "イーライリリー",         "en": "eli lilly"},
            {"ticker": "AMGN",  "name": "アムジェン",             "en": "amgen"},
            {"ticker": "GILD",  "name": "ギリアド",               "en": "gilead sciences"},
            {"ticker": "BMY",   "name": "ブリストル・マイヤーズ", "en": "bristol myers squibb bms"},
            {"ticker": "ISRG",  "name": "インテュイティブ・サージカル","en": "intuitive surgical"},
        ],
        "金融": [
            {"ticker": "JPM",   "name": "JPモルガン",             "en": "jpmorgan chase"},
            {"ticker": "BAC",   "name": "バンク・オブ・アメリカ", "en": "bank of america"},
            {"ticker": "WFC",   "name": "ウェルズ・ファーゴ",     "en": "wells fargo"},
            {"ticker": "GS",    "name": "ゴールドマン・サックス", "en": "goldman sachs"},
            {"ticker": "MS",    "name": "モルガン・スタンレー",   "en": "morgan stanley"},
            {"ticker": "BRK-B", "name": "バークシャー・ハサウェイ","en": "berkshire hathaway buffett"},
            {"ticker": "V",     "name": "ビザ",                   "en": "visa"},
            {"ticker": "MA",    "name": "マスターカード",         "en": "mastercard"},
            {"ticker": "AXP",   "name": "アメリカン・エキスプレス","en": "american express amex"},
            {"ticker": "COIN",  "name": "コインベース",           "en": "coinbase crypto"},
            {"ticker": "PYPL",  "name": "ペイパル",               "en": "paypal"},
        ],
        "消費・小売": [
            {"ticker": "AMZN",  "name": "アマゾン",               "en": "amazon"},
            {"ticker": "TSLA",  "name": "テスラ",                 "en": "tesla elon musk"},
            {"ticker": "WMT",   "name": "ウォルマート",           "en": "walmart"},
            {"ticker": "COST",  "name": "コストコ",               "en": "costco"},
            {"ticker": "NKE",   "name": "ナイキ",                 "en": "nike"},
            {"ticker": "MCD",   "name": "マクドナルド",           "en": "mcdonalds"},
            {"ticker": "SBUX",  "name": "スターバックス",         "en": "starbucks"},
            {"ticker": "UBER",  "name": "ウーバー",               "en": "uber"},
            {"ticker": "ABNB",  "name": "エアビーアンドビー",     "en": "airbnb"},
            {"ticker": "BKNG",  "name": "ブッキング・ホールディングス","en": "booking holdings priceline"},
        ],
        "エネルギー": [
            {"ticker": "XOM",   "name": "エクソンモービル",       "en": "exxon mobil"},
            {"ticker": "CVX",   "name": "シェブロン",             "en": "chevron"},
            {"ticker": "COP",   "name": "コノコフィリップス",     "en": "conocophillips"},
            {"ticker": "SLB",   "name": "シュルンベルジェ",       "en": "schlumberger"},
            {"ticker": "OXY",   "name": "オクシデンタル・ペトロリアム","en": "occidental petroleum"},
        ],
        "通信・メディア": [
            {"ticker": "NFLX",  "name": "ネットフリックス",       "en": "netflix"},
            {"ticker": "DIS",   "name": "ウォルト・ディズニー",   "en": "disney walt"},
            {"ticker": "T",     "name": "AT&T",                   "en": "att at&t"},
            {"ticker": "VZ",    "name": "ベライゾン",             "en": "verizon"},
            {"ticker": "CMCSA", "name": "コムキャスト",           "en": "comcast nbc"},
            {"ticker": "SPOT",  "name": "スポティファイ",         "en": "spotify"},
        ],
        "NASDAQ100": [
            {"ticker": "AAPL",  "name": "アップル",               "en": "apple"},
            {"ticker": "MSFT",  "name": "マイクロソフト",         "en": "microsoft"},
            {"ticker": "NVDA",  "name": "エヌビディア",           "en": "nvidia"},
            {"ticker": "AMZN",  "name": "アマゾン",               "en": "amazon"},
            {"ticker": "META",  "name": "メタ",                   "en": "meta facebook"},
            {"ticker": "GOOGL", "name": "グーグル",               "en": "google"},
            {"ticker": "TSLA",  "name": "テスラ",                 "en": "tesla"},
            {"ticker": "AVGO",  "name": "ブロードコム",           "en": "broadcom"},
            {"ticker": "COST",  "name": "コストコ",               "en": "costco"},
            {"ticker": "NFLX",  "name": "ネットフリックス",       "en": "netflix"},
            {"ticker": "AMD",   "name": "AMD",                    "en": "amd"},
            {"ticker": "QCOM",  "name": "クアルコム",             "en": "qualcomm"},
            {"ticker": "ADBE",  "name": "アドビ",                 "en": "adobe"},
            {"ticker": "CSCO",  "name": "シスコシステムズ",       "en": "cisco systems"},
            {"ticker": "PYPL",  "name": "ペイパル",               "en": "paypal"},
            {"ticker": "INTC",  "name": "インテル",               "en": "intel"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ","en": "applied materials"},
            {"ticker": "MU",    "name": "マイクロン",             "en": "micron"},
            {"ticker": "ISRG",  "name": "インテュイティブ・サージカル","en": "intuitive surgical"},
            {"ticker": "MELI",  "name": "メルカドリブレ",         "en": "mercadolibre"},
        ],
        "S&P500 注目": [
            {"ticker": "AAPL",  "name": "アップル",               "en": "apple"},
            {"ticker": "MSFT",  "name": "マイクロソフト",         "en": "microsoft"},
            {"ticker": "AMZN",  "name": "アマゾン",               "en": "amazon"},
            {"ticker": "NVDA",  "name": "エヌビディア",           "en": "nvidia"},
            {"ticker": "GOOGL", "name": "グーグル",               "en": "google"},
            {"ticker": "META",  "name": "メタ",                   "en": "meta facebook"},
            {"ticker": "BRK-B", "name": "バークシャー・ハサウェイ","en": "berkshire hathaway"},
            {"ticker": "LLY",   "name": "イーライリリー",         "en": "eli lilly"},
            {"ticker": "JPM",   "name": "JPモルガン",             "en": "jpmorgan"},
            {"ticker": "TSLA",  "name": "テスラ",                 "en": "tesla"},
            {"ticker": "V",     "name": "ビザ",                   "en": "visa"},
            {"ticker": "UNH",   "name": "ユナイテッドヘルス",     "en": "unitedhealth"},
            {"ticker": "XOM",   "name": "エクソンモービル",       "en": "exxon"},
            {"ticker": "JNJ",   "name": "ジョンソン＆ジョンソン", "en": "johnson"},
            {"ticker": "WMT",   "name": "ウォルマート",           "en": "walmart"},
            {"ticker": "MA",    "name": "マスターカード",         "en": "mastercard"},
            {"ticker": "AVGO",  "name": "ブロードコム",           "en": "broadcom"},
            {"ticker": "COST",  "name": "コストコ",               "en": "costco"},
            {"ticker": "NFLX",  "name": "ネットフリックス",       "en": "netflix"},
            {"ticker": "CRM",   "name": "セールスフォース",       "en": "salesforce"},
        ],
    },
    "OTHER": {
        "仮想通貨関連": [
            {"ticker": "COIN",  "name": "コインベース",           "en": "coinbase crypto bitcoin"},
            {"ticker": "MSTR",  "name": "マイクロストラテジー",   "en": "microstrategy bitcoin"},
            {"ticker": "RIOT",  "name": "ライオット・プラットフォームズ","en": "riot platforms mining"},
            {"ticker": "MARA",  "name": "マラソン・デジタル",     "en": "marathon digital mining"},
            {"ticker": "CLSK",  "name": "クリーンスパーク",       "en": "cleanspark"},
            {"ticker": "HUT",   "name": "ハット8",                "en": "hut 8 mining"},
            {"ticker": "CIFR",  "name": "サイファー・マイニング", "en": "cipher mining"},
        ],
        "AI・半導体関連": [
            {"ticker": "NVDA",  "name": "エヌビディア",           "en": "nvidia ai gpu"},
            {"ticker": "AMD",   "name": "AMD",                    "en": "amd"},
            {"ticker": "ARM",   "name": "アーム",                 "en": "arm chip"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ",       "en": "supermicro"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ","en": "applied materials"},
            {"ticker": "ASML",  "name": "ASML",                   "en": "asml lithography"},
            {"ticker": "MU",    "name": "マイクロン",             "en": "micron memory"},
            {"ticker": "LRCX",  "name": "ラムリサーチ",           "en": "lam research"},
            {"ticker": "KLAC",  "name": "KLA",                    "en": "kla"},
        ],
        "ETF（米国）": [
            {"ticker": "SPY",   "name": "S&P500 ETF (SPY)",       "en": "sp500 spy etf index"},
            {"ticker": "QQQ",   "name": "NASDAQ100 ETF (QQQ)",    "en": "nasdaq qqq"},
            {"ticker": "VTI",   "name": "全米株式 ETF (VTI)",     "en": "total market vti vanguard"},
            {"ticker": "GLD",   "name": "金 ETF (GLD)",           "en": "gold gld"},
            {"ticker": "TLT",   "name": "長期国債 ETF (TLT)",     "en": "treasury bond tlt"},
            {"ticker": "ARKK",  "name": "ARK Innovation ETF",     "en": "ark innovation cathie wood"},
            {"ticker": "SOXL",  "name": "半導体 3倍ブル (SOXL)",  "en": "semiconductor bull soxl"},
            {"ticker": "SOXS",  "name": "半導体 3倍ベア (SOXS)",  "en": "semiconductor bear soxs"},
            {"ticker": "TQQQ",  "name": "NASDAQ100 3倍ブル (TQQQ)","en": "nasdaq bull tqqq"},
            {"ticker": "SPXL",  "name": "S&P500 3倍ブル (SPXL)",  "en": "sp500 bull spxl"},
            {"ticker": "IWM",   "name": "Russell2000 ETF (IWM)",  "en": "russell small cap iwm"},
        ],
        "指数連動": [
            {"ticker": "^N225", "name": "日経225",                "en": "nikkei 225 japan"},
            {"ticker": "^GSPC", "name": "S&P500",                 "en": "sp500 us index"},
            {"ticker": "^IXIC", "name": "NASDAQ",                 "en": "nasdaq composite"},
            {"ticker": "^DJI",  "name": "ダウ平均",               "en": "dow jones djia"},
            {"ticker": "^RUT",  "name": "Russell2000",            "en": "russell small"},
            {"ticker": "^HSI",  "name": "香港ハンセン",           "en": "hong kong hang seng hsi"},
            {"ticker": "^FTSE", "name": "FTSE100",                "en": "ftse uk london"},
            {"ticker": "^GDAXI","name": "DAX（独）",              "en": "dax germany"},
        ],
    },
}
