"""銘柄スクリーナー データベース (カテゴリ別)"""

SCREENER: dict = {
    "JP": {
        "電機・半導体": [
            {"ticker": "6758.T", "name": "ソニーグループ"},
            {"ticker": "6861.T", "name": "キーエンス"},
            {"ticker": "6857.T", "name": "アドバンテスト"},
            {"ticker": "8035.T", "name": "東京エレクトロン"},
            {"ticker": "6920.T", "name": "レーザーテック"},
            {"ticker": "6645.T", "name": "オムロン"},
            {"ticker": "6702.T", "name": "富士通"},
            {"ticker": "6701.T", "name": "NEC"},
            {"ticker": "6752.T", "name": "パナソニック"},
            {"ticker": "6971.T", "name": "京セラ"},
            {"ticker": "6963.T", "name": "ローム"},
            {"ticker": "6594.T", "name": "日本電産"},
            {"ticker": "6501.T", "name": "日立製作所"},
            {"ticker": "6503.T", "name": "三菱電機"},
            {"ticker": "6506.T", "name": "安川電機"},
        ],
        "自動車・輸送機器": [
            {"ticker": "7203.T", "name": "トヨタ自動車"},
            {"ticker": "7267.T", "name": "ホンダ"},
            {"ticker": "7269.T", "name": "スズキ"},
            {"ticker": "7201.T", "name": "日産自動車"},
            {"ticker": "7270.T", "name": "SUBARU"},
            {"ticker": "7261.T", "name": "マツダ"},
            {"ticker": "7011.T", "name": "三菱重工業"},
            {"ticker": "7013.T", "name": "IHI"},
            {"ticker": "6326.T", "name": "クボタ"},
            {"ticker": "7751.T", "name": "キヤノン"},
        ],
        "銀行・金融": [
            {"ticker": "8306.T", "name": "三菱UFJフィナンシャル"},
            {"ticker": "8316.T", "name": "三井住友フィナンシャル"},
            {"ticker": "8411.T", "name": "みずほフィナンシャル"},
            {"ticker": "8591.T", "name": "オリックス"},
            {"ticker": "8766.T", "name": "東京海上ホールディングス"},
            {"ticker": "8725.T", "name": "MS&ADインシュアランス"},
            {"ticker": "8604.T", "name": "野村ホールディングス"},
            {"ticker": "8308.T", "name": "りそなホールディングス"},
        ],
        "通信・IT": [
            {"ticker": "9984.T", "name": "ソフトバンクグループ"},
            {"ticker": "9432.T", "name": "NTT"},
            {"ticker": "9433.T", "name": "KDDI"},
            {"ticker": "9434.T", "name": "ソフトバンク"},
            {"ticker": "4385.T", "name": "メルカリ"},
            {"ticker": "4689.T", "name": "LINEヤフー"},
            {"ticker": "3697.T", "name": "SHIFT"},
            {"ticker": "4307.T", "name": "野村総合研究所"},
        ],
        "小売・消費": [
            {"ticker": "9983.T", "name": "ファーストリテイリング"},
            {"ticker": "3382.T", "name": "セブン&アイ"},
            {"ticker": "8267.T", "name": "イオン"},
            {"ticker": "2802.T", "name": "味の素"},
            {"ticker": "2914.T", "name": "日本たばこ産業"},
            {"ticker": "2503.T", "name": "キリンホールディングス"},
            {"ticker": "2502.T", "name": "アサヒグループ"},
            {"ticker": "7453.T", "name": "良品計画"},
            {"ticker": "3086.T", "name": "J.フロント リテイリング"},
        ],
        "ゲーム・エンタメ": [
            {"ticker": "7974.T", "name": "任天堂"},
            {"ticker": "3659.T", "name": "ネクソン"},
            {"ticker": "9684.T", "name": "スクウェア・エニックス"},
            {"ticker": "7832.T", "name": "バンダイナムコ"},
            {"ticker": "3765.T", "name": "ガンホー"},
            {"ticker": "6460.T", "name": "セガサミー"},
            {"ticker": "2432.T", "name": "DeNA"},
            {"ticker": "3632.T", "name": "グリー"},
        ],
        "製薬・ヘルスケア": [
            {"ticker": "4568.T", "name": "第一三共"},
            {"ticker": "4519.T", "name": "中外製薬"},
            {"ticker": "4523.T", "name": "エーザイ"},
            {"ticker": "4503.T", "name": "アステラス製薬"},
            {"ticker": "4543.T", "name": "テルモ"},
            {"ticker": "4151.T", "name": "協和キリン"},
            {"ticker": "4507.T", "name": "塩野義製薬"},
        ],
        "素材・化学": [
            {"ticker": "4063.T", "name": "信越化学工業"},
            {"ticker": "4188.T", "name": "三菱ケミカル"},
            {"ticker": "5401.T", "name": "日本製鉄"},
            {"ticker": "3407.T", "name": "旭化成"},
            {"ticker": "4005.T", "name": "住友化学"},
            {"ticker": "5713.T", "name": "住友金属鉱山"},
        ],
        "不動産・建設": [
            {"ticker": "1925.T", "name": "大和ハウス工業"},
            {"ticker": "1928.T", "name": "積水ハウス"},
            {"ticker": "8801.T", "name": "三井不動産"},
            {"ticker": "8802.T", "name": "三菱地所"},
            {"ticker": "8830.T", "name": "住友不動産"},
            {"ticker": "1963.T", "name": "日揮ホールディングス"},
        ],
        "エネルギー・資源": [
            {"ticker": "5020.T", "name": "ENEOSホールディングス"},
            {"ticker": "9501.T", "name": "東京電力"},
            {"ticker": "9531.T", "name": "東京ガス"},
            {"ticker": "1605.T", "name": "INPEX"},
        ],
    },
    "US": {
        "テクノロジー": [
            {"ticker": "AAPL",  "name": "アップル"},
            {"ticker": "MSFT",  "name": "マイクロソフト"},
            {"ticker": "GOOGL", "name": "グーグル"},
            {"ticker": "META",  "name": "メタ"},
            {"ticker": "NVDA",  "name": "エヌビディア"},
            {"ticker": "AMD",   "name": "AMD"},
            {"ticker": "INTC",  "name": "インテル"},
            {"ticker": "ORCL",  "name": "オラクル"},
            {"ticker": "CRM",   "name": "セールスフォース"},
            {"ticker": "ADBE",  "name": "アドビ"},
            {"ticker": "QCOM",  "name": "クアルコム"},
            {"ticker": "TXN",   "name": "テキサス・インスツルメンツ"},
            {"ticker": "AVGO",  "name": "ブロードコム"},
            {"ticker": "ARM",   "name": "アーム"},
            {"ticker": "PLTR",  "name": "パランティア"},
            {"ticker": "SNOW",  "name": "スノーフレーク"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ"},
            {"ticker": "MU",    "name": "マイクロン"},
            {"ticker": "LRCX",  "name": "ラムリサーチ"},
        ],
        "AI・クラウド": [
            {"ticker": "NVDA",  "name": "エヌビディア"},
            {"ticker": "MSFT",  "name": "マイクロソフト"},
            {"ticker": "GOOGL", "name": "グーグル"},
            {"ticker": "AMZN",  "name": "アマゾン"},
            {"ticker": "META",  "name": "メタ"},
            {"ticker": "CRM",   "name": "セールスフォース"},
            {"ticker": "PLTR",  "name": "パランティア"},
            {"ticker": "SNOW",  "name": "スノーフレーク"},
            {"ticker": "ARM",   "name": "アーム"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ"},
            {"ticker": "DELL",  "name": "デル・テクノロジーズ"},
            {"ticker": "HPE",   "name": "ヒューレット・パッカード"},
        ],
        "ヘルスケア": [
            {"ticker": "JNJ",   "name": "ジョンソン＆ジョンソン"},
            {"ticker": "UNH",   "name": "ユナイテッドヘルス"},
            {"ticker": "PFE",   "name": "ファイザー"},
            {"ticker": "MRK",   "name": "メルク"},
            {"ticker": "ABBV",  "name": "アッヴィ"},
            {"ticker": "LLY",   "name": "イーライリリー"},
            {"ticker": "AMGN",  "name": "アムジェン"},
            {"ticker": "GILD",  "name": "ギリアド"},
            {"ticker": "BMY",   "name": "ブリストル・マイヤーズ"},
            {"ticker": "ISRG",  "name": "インテュイティブ・サージカル"},
        ],
        "金融": [
            {"ticker": "JPM",   "name": "JPモルガン"},
            {"ticker": "BAC",   "name": "バンク・オブ・アメリカ"},
            {"ticker": "WFC",   "name": "ウェルズ・ファーゴ"},
            {"ticker": "GS",    "name": "ゴールドマン・サックス"},
            {"ticker": "MS",    "name": "モルガン・スタンレー"},
            {"ticker": "BRK-B", "name": "バークシャー・ハサウェイ"},
            {"ticker": "V",     "name": "ビザ"},
            {"ticker": "MA",    "name": "マスターカード"},
            {"ticker": "AXP",   "name": "アメリカン・エキスプレス"},
            {"ticker": "COIN",  "name": "コインベース"},
            {"ticker": "PYPL",  "name": "ペイパル"},
        ],
        "消費・小売": [
            {"ticker": "AMZN",  "name": "アマゾン"},
            {"ticker": "TSLA",  "name": "テスラ"},
            {"ticker": "WMT",   "name": "ウォルマート"},
            {"ticker": "COST",  "name": "コストコ"},
            {"ticker": "NKE",   "name": "ナイキ"},
            {"ticker": "MCD",   "name": "マクドナルド"},
            {"ticker": "SBUX",  "name": "スターバックス"},
            {"ticker": "UBER",  "name": "ウーバー"},
            {"ticker": "ABNB",  "name": "エアビーアンドビー"},
            {"ticker": "BKNG",  "name": "ブッキング・ホールディングス"},
        ],
        "エネルギー": [
            {"ticker": "XOM",   "name": "エクソンモービル"},
            {"ticker": "CVX",   "name": "シェブロン"},
            {"ticker": "COP",   "name": "コノコフィリップス"},
            {"ticker": "SLB",   "name": "シュルンベルジェ"},
            {"ticker": "OXY",   "name": "オクシデンタル・ペトロリアム"},
        ],
        "通信・メディア": [
            {"ticker": "NFLX",  "name": "ネットフリックス"},
            {"ticker": "DIS",   "name": "ウォルト・ディズニー"},
            {"ticker": "T",     "name": "AT&T"},
            {"ticker": "VZ",    "name": "ベライゾン"},
            {"ticker": "CMCSA", "name": "コムキャスト"},
            {"ticker": "SPOT",  "name": "スポティファイ"},
        ],
        "NASDAQ100": [
            {"ticker": "AAPL",  "name": "アップル"},
            {"ticker": "MSFT",  "name": "マイクロソフト"},
            {"ticker": "NVDA",  "name": "エヌビディア"},
            {"ticker": "AMZN",  "name": "アマゾン"},
            {"ticker": "META",  "name": "メタ"},
            {"ticker": "GOOGL", "name": "グーグル"},
            {"ticker": "TSLA",  "name": "テスラ"},
            {"ticker": "AVGO",  "name": "ブロードコム"},
            {"ticker": "COST",  "name": "コストコ"},
            {"ticker": "NFLX",  "name": "ネットフリックス"},
            {"ticker": "AMD",   "name": "AMD"},
            {"ticker": "QCOM",  "name": "クアルコム"},
            {"ticker": "ADBE",  "name": "アドビ"},
            {"ticker": "CSCO",  "name": "シスコシステムズ"},
            {"ticker": "PYPL",  "name": "ペイパル"},
            {"ticker": "INTC",  "name": "インテル"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ"},
            {"ticker": "MU",    "name": "マイクロン"},
            {"ticker": "ISRG",  "name": "インテュイティブ・サージカル"},
            {"ticker": "MELI",  "name": "メルカドリブレ"},
        ],
        "S&P500 注目": [
            {"ticker": "AAPL",  "name": "アップル"},
            {"ticker": "MSFT",  "name": "マイクロソフト"},
            {"ticker": "AMZN",  "name": "アマゾン"},
            {"ticker": "NVDA",  "name": "エヌビディア"},
            {"ticker": "GOOGL", "name": "グーグル"},
            {"ticker": "META",  "name": "メタ"},
            {"ticker": "BRK-B", "name": "バークシャー・ハサウェイ"},
            {"ticker": "LLY",   "name": "イーライリリー"},
            {"ticker": "JPM",   "name": "JPモルガン"},
            {"ticker": "TSLA",  "name": "テスラ"},
            {"ticker": "V",     "name": "ビザ"},
            {"ticker": "UNH",   "name": "ユナイテッドヘルス"},
            {"ticker": "XOM",   "name": "エクソンモービル"},
            {"ticker": "JNJ",   "name": "ジョンソン＆ジョンソン"},
            {"ticker": "WMT",   "name": "ウォルマート"},
            {"ticker": "MA",    "name": "マスターカード"},
            {"ticker": "AVGO",  "name": "ブロードコム"},
            {"ticker": "COST",  "name": "コストコ"},
            {"ticker": "NFLX",  "name": "ネットフリックス"},
            {"ticker": "CRM",   "name": "セールスフォース"},
        ],
    },
    "OTHER": {
        "仮想通貨関連": [
            {"ticker": "COIN",  "name": "コインベース"},
            {"ticker": "MSTR",  "name": "マイクロストラテジー"},
            {"ticker": "RIOT",  "name": "ライオット・プラットフォームズ"},
            {"ticker": "MARA",  "name": "マラソン・デジタル"},
            {"ticker": "CLSK",  "name": "クリーンスパーク"},
            {"ticker": "HUT",   "name": "ハット8"},
            {"ticker": "CIFR",  "name": "サイファー・マイニング"},
        ],
        "AI・半導体関連": [
            {"ticker": "NVDA",  "name": "エヌビディア"},
            {"ticker": "AMD",   "name": "AMD"},
            {"ticker": "ARM",   "name": "アーム"},
            {"ticker": "SMCI",  "name": "スーパーマイクロ"},
            {"ticker": "AMAT",  "name": "アプライド・マテリアルズ"},
            {"ticker": "ASML",  "name": "ASML"},
            {"ticker": "MU",    "name": "マイクロン"},
            {"ticker": "LRCX",  "name": "ラムリサーチ"},
            {"ticker": "KLAC",  "name": "KLA"},
        ],
        "ETF（米国）": [
            {"ticker": "SPY",   "name": "S&P500 ETF (SPY)"},
            {"ticker": "QQQ",   "name": "NASDAQ100 ETF (QQQ)"},
            {"ticker": "VTI",   "name": "全米株式 ETF (VTI)"},
            {"ticker": "GLD",   "name": "金 ETF (GLD)"},
            {"ticker": "TLT",   "name": "長期国債 ETF (TLT)"},
            {"ticker": "ARKK",  "name": "ARK Innovation ETF"},
            {"ticker": "SOXL",  "name": "半導体 3倍ブル (SOXL)"},
            {"ticker": "SOXS",  "name": "半導体 3倍ベア (SOXS)"},
            {"ticker": "TQQQ",  "name": "NASDAQ100 3倍ブル (TQQQ)"},
            {"ticker": "SPXL",  "name": "S&P500 3倍ブル (SPXL)"},
            {"ticker": "IWM",   "name": "Russell2000 ETF (IWM)"},
        ],
        "指数連動": [
            {"ticker": "^N225", "name": "日経225"},
            {"ticker": "^GSPC", "name": "S&P500"},
            {"ticker": "^IXIC", "name": "NASDAQ"},
            {"ticker": "^DJI",  "name": "ダウ平均"},
            {"ticker": "^RUT",  "name": "Russell2000"},
            {"ticker": "^HSI",  "name": "香港ハンセン"},
            {"ticker": "^FTSE", "name": "FTSE100"},
            {"ticker": "^GDAXI","name": "DAX（独）"},
        ],
    },
}
